// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBF05qty6lDTV21gALzlnUOPf1LiLkafuk',
    appId: '1:339977187902:web:8b2f98b51b0cf3c69f176f',
    messagingSenderId: '339977187902',
    projectId: 'flutter-chat-app-145d5',
    authDomain: 'flutter-chat-app-145d5.firebaseapp.com',
    storageBucket: 'flutter-chat-app-145d5.appspot.com',
    measurementId: 'G-J9CP874FFS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCn-yuWpqlWeLU0Vhd8y6zwBXinWKhb9Uc',
    appId: '1:339977187902:android:07e1cc921f97f76f9f176f',
    messagingSenderId: '339977187902',
    projectId: 'flutter-chat-app-145d5',
    storageBucket: 'flutter-chat-app-145d5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUtXAROHQ4KNXz6ylPWSid30-2oxrYC2k',
    appId: '1:339977187902:ios:8707bde2bce8f4659f176f',
    messagingSenderId: '339977187902',
    projectId: 'flutter-chat-app-145d5',
    storageBucket: 'flutter-chat-app-145d5.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAUtXAROHQ4KNXz6ylPWSid30-2oxrYC2k',
    appId: '1:339977187902:ios:c252a237445a142d9f176f',
    messagingSenderId: '339977187902',
    projectId: 'flutter-chat-app-145d5',
    storageBucket: 'flutter-chat-app-145d5.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
